[CTB-122] Wallet Withdraw endpoint
PZ-CTB/ctb-backend pull request #32
Opened 2023-04-24 21:40 UTC by PiotrDeda

2023-04-30 18:12 UTC, mik-sondej submitted a review, later dismissed

2023-04-30 21:02 UTC, vis4rd requested changes

2023-04-30 21:04 UTC, PiotrDeda commented on tests/server/test_server.py
>                      # noinspection PyTypeChecker
Because you don't use a good IDE like PyCharm.

2023-04-30 21:04 UTC, PiotrDeda commented on src/server/responses.py
> +        """409: user tried to withdraw more money than he has."""
Project canceled

2023-04-30 21:07 UTC, vis4rd commented on tests/server/test_server.py
>                      # noinspection PyTypeChecker
Python interpreter inside my brain tells me that those types match, maybe I am mistaken?

2023-04-30 21:49 UTC, PiotrDeda commented on tests/server/test_server.py
>                      # noinspection PyTypeChecker
They do, it's a type checker mistake.

2023-05-05 21:06 UTC, vis4rd approved these changes

2023-05-06 06:46 UTC, unlvy approved these changes

2023-05-06 13:30 UTC, merged