Updated Dockerfile
PZ-CTB/ctb-backend pull request #46
Opened 2023-05-30 08:44 UTC by pawel2000pl

Wykonano zgodnie z zadaniem: instalacja modułów modelu w kontenerze.

Zastanawiam się tylko, czy to dawać na master, czy w razie potrzeby zrobi się merge do innej istniejącej gałęzi.

2023-05-30 10:52 UTC, unlvy commented
It has to be merged directly into master branch. 
Please update pr name to match jira task

2023-05-30 10:56 UTC, rafalw99 approved these changes

2023-05-30 10:59 UTC, unlvy requested changes
Please do not merge before today`s meeting

2023-07-24 12:59 UTC, unlvy approved these changes

2023-07-24 13:02 UTC, PiotrDeda approved these changes

2023-07-25 09:16 UTC, merged